# Generated by Django 4.1.5 on 2023-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=60)),
                ('confirm_password', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('pincode', models.TextField()),
            ],
        ),
    ]
