# Generated by Django 4.1.5 on 2023-02-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpage',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
