# Generated by Django 4.1.5 on 2023-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_subscription_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contact',
            field=models.CharField(max_length=12),
        ),
    ]
