# Generated by Django 4.1.5 on 2023-02-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userdetails_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginPage',
        ),
    ]
