# Generated by Django 4.1.5 on 2023-02-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(default=2, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
