# Generated by Django 4.1.5 on 2023-02-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='web.category'),
        ),
    ]
