# Generated by Django 4.1.5 on 2023-02-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_productdetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
    ]
