# Generated by Django 4.1.5 on 2023-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_brand_details_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='price',
        ),
        migrations.AddField(
            model_name='details',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
