# Generated by Django 4.1.5 on 2023-02-06 14:53

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_category_product_remove_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
                ('the_json', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.product'),
        ),
    ]
