# Generated by Django 4.1.5 on 2023-02-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=2, upload_to='img/'),
            preserve_default=False,
        ),
    ]
