# Generated by Django 4.1.5 on 2023-02-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
